name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'artifacts/models/bestmodel.pkl'
      - 'artifacts/preprocessors/**'
      - 'requirements.txt'
      - '.github/workflows/docker-image.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Model Artifacts
      uses: actions/download-artifact@v3
      with:
        name: models
        path: artifacts/models/
    - name: Download Preprocessor Artifacts
      uses: actions/download-artifact@v3
      with:
        name: preprocessors
        path: artifacts/preprocessors/

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/customer-churn-api:latest
