name: Model Evaluation

on:
  push:
    branches: [main]
    paths:
      - 'src/evaluate_models.py'
      - 'artifacts/models/**'

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Model Artifacts
      uses: actions/download-artifact@v2
      with:
        name: models
        path: artifacts/models/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Model Evaluation
      run: |
        python src/evaluate_models.py

    - name: Upload Evaluation Metrics
      uses: actions/upload-artifact@v2
      with:
        name: metrics
        path: artifacts/metrics/
