name: Data Preprocessing

on:
  push:
    branches: [main]
    paths:
      - 'src/data_preprocess.py'
      - 'data/**'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Data Preprocessing
      run: |
        python src/data_preprocess.py

    - name: Upload Preprocessor Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: preprocessors
        path: artifacts/preprocessors/
