name: Model Training

on:
  push:
    branches: [main]
    paths:
      - 'src/train_models.py'
      - 'artifacts/preprocessors/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Preprocessor Artifacts
      uses: actions/download-artifact@v2
      with:
        name: preprocessors
        path: artifacts/preprocessors/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Model Training
      run: |
        python src/train_models.py

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: models
        path: artifacts/models/
